"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const videoCall_controller_1 = require("../controllers/videoCall.controller");
const asyncHandler_1 = require("../middlewares/asyncHandler");
const router = (0, express_1.Router)();
router.post('/create', (0, asyncHandler_1.asyncHandler)(videoCall_controller_1.createRoom));
router.post('/join', (0, asyncHandler_1.asyncHandler)(videoCall_controller_1.joinRoom));
router.get('/:roomCode', (0, asyncHandler_1.asyncHandler)(videoCall_controller_1.getRoomInfo));
exports.default = router;
