# TURN Local (no TLS)
listening-port=3478
listening-ip=0.0.0.0

realm=local
use-auth-secret
static-auth-secret=${TURN_SECRET}

fingerprint
stale-nonce
no-loopback-peers
no-multicast-peers
simple-log
log-file=/var/log/turnserver/turn-local.log

max-bps=4000000
total-quota=50
user-quota=5
